### ISSUE TITLE
Carthage produces framework with invalid CFBundleShortVersionString for App Store

### ISSUE THREAD

**Issue by hixfield** [ephread/Instructions#123]
My cart file:

github "ephread/Instructions" "1.0.0-beta.1"

The framework building works fine, all is ok, but when trying to push the app to the apple App Store the following error is returned:

ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '1.0.0-beta.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."

I guess we should simply update the version of the framework to "1.0.1" add this as a tag to the repo and use that in carthage? I will create a pull request

**Comment by ephread** [comment]
Hey @hixfield! That's a dup of #120, but you're right, it's been lingering for a bit too long in beta. I haven't encountered any new bug, so I'd say it's okay to bump it to 1.0.0.

Thanks for the PR, can you update it to use `1.0.0` instead of `1.0.1`? I'll merge it and create the appropriate releases.

**Comment by hixfield** [comment]
done, go ahead!

**Comment by ephread** [comment]
1.0.0 was released few minutes ago!

**Comment by hixfield** [comment]
:-) teamwork!
