### ISSUE TITLE
set arrowOrientation,but coachMarkBodyView in a wrong position

### ISSUE THREAD

**Issue by roylly** [ephread/Instructions#177]
**Describe the bug**
[  public func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkViewsAt index: Int, madeFrom coachMark: CoachMark) -> (bodyView: CoachMarkBodyView, arrowView: CoachMarkArrowView?) {
        var desc = ""
        switch index {
        case 0:
            desc = "点击这里，获得帮助"
        case 1:
            desc = "相机扫描数独区域，以AR的形式展示数独的答案"
        case 2:
            desc = "相机扫描数独区域，获得数独的答案"
        case 3:
            desc = "从相册选择一张数独的截屏或者照片，得到数独答案"
        default:
            desc = "帮助功能引导"
        }
        let coachViews = coachMarksController.helper.makeDefaultCoachViews(withArrow: true, arrowOrientation:.top, hintText: desc, nextText: nil)
        return (bodyView: coachViews.bodyView, arrowView: coachViews.arrowView)
    }]

**To Reproduce**
[set the arrow orientation to a custom orientation, for example "top", when the target view's position become half bottom of the screen , the arrow orientation is right as you set "top",while the bodyView of the coachMark 's position are wrong ]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[
![simulator screen shot - iphone x - 2018-08-13 at 20 45 33](https://user-images.githubusercontent.com/7507767/44032839-f8593744-9f3a-11e8-894b-d2f0c217d3e1.png)
.]

**Environment:**
 - Device: [ iPhone X]
 - iOS version : [ 11.4]

**Additional context**
[Add any other context about the problem here.]

**Comment by ephread** [comment]
This bit:

```swift
    let coachViews = coachMarksController.helper.makeDefaultCoachViews(withArrow: true, arrowOrientation:.top, hintText: desc, nextText: nil)
```

doesn't set the orientation. It creates and returns the default views according to the provided parameters.

If you want the coach mark at index 3 to show under the cutout path, you should set:

```swift
    coachMark.arrowOrientation = .top
```

in

```
    coachMarksController(_:, coachMarkAt:)
```

In `makeDefaultCoachViews(withArrow:, arrowOrientation:, hintText:, nextText:)`, it's generally a good idea to pass `coachMark.arrowOrientation` rather than a literal enum. That way you only have to set the orientation once.

---

`arrowOrientation` is a bit confusing. I plan to rename it to something like `coachMarkPosition`, with `.top`, `.bottom`, `.left` and `.right` positioning the coach mark where expected.

**Comment by roylly** [comment]
thanks for your help，got it.
