### ISSUE TITLE
CoachMarker applied to tableViewCell returns wrong position

### ISSUE THREAD

**Issue by nstele** [ephread/Instructions#178]
**Describe the bug**
I've tried to apply the coach marker to a view that is inside a TableViewCell , for some reason for non iphone X phones doesn't work and for iphone X works perfect.

**To Reproduce**
```
 cell = tableView.dequeueReusableCell(withIdentifier: DashboardOptionsTableViewCell.identifier)
            if let dashboardOptionsCell = cell as? DashboardOptionsTableViewCell {
                dashboardOptionsCell.delegate = self
                dashboardOptionsCell.parent = self
                self.coachMarkCell = coachMarksController.helper.makeCoachMark(for: dashboardOptionsCell.wizardsView)
            }

 func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
        _ = UIView()
        return coachMarkCell!
    }

```
**Expected behavior**

The coach marker should have the same position for any screen size
**Screenshots**
**Environment:**

 - Device: [e.g. iPhone X, iphone 7 plus, simulator]
 - iOS version : [e.g. 11.3]

**Additional context**
[Add any other context about the problem here.]

**Comment by ephread** [comment]
Hi @nstele, thanks for reporting the issue.

Looks a lot like a safe area issue. I pushed a possible fix to `master` a while ago, but I haven't release a new version yet. Would you be able to give `master`'s `HEAD` a try and tell me if the issue is still occurring?

You'll probably need to install Git LFS to be able to clone the repo and fetch the revisions after e3593609.

---

Possibly related to [169#397830863](https://github.com/ephread/Instructions/issues/169#issuecomment-397830863), #173 and #176.

**Comment by nstele** [comment]
@ephread I'm using cocoapods, is posible to use cocoapods pointing to this commit?

**Comment by ephread** [comment]
> I'm using cocoapods, is posible to use cocoapods pointing to this commit?

Yes, exactly the way you did. You don't need to point specifically to this specific commit though, it was just a heads up about git LFS.

> I'm trying with but the issue still there

Alright, so it's probably not related to the safe areas. Upon further inspection of your code, I noticed that you're creating `coachMarksController.helper.makeCoachMark(for: dashboardOptionsCell.wizardsView)` in `dequeueReusableCell` which is most likely called before the layout pass occurred.

`helper.makeCoachMark` will take the current frame of the provided view, so the result might undefined if it's called before the layout pass.

What happens if you move the creation of the coachmark to `viewWillAppear` instead?

**Comment by nstele** [comment]
@ephread is weird that works fine for iphone X

**Comment by nstele** [comment]
I was able to solve the issue removing the creation of the CoachMark outside the method cellForRowAtIndexPath, maintaining a reference to the cell from my VC. Thanks

**Comment by ephread** [comment]
> is weird that works fine for iphone X

Definitely weird, I don't know why.

> I was able to solve the issue

Awesome, I'm glad to hear that!
