### ISSUE TITLE
didHide delegate reports wrong indexes

### ISSUE THREAD

**Issue by Mattijah** [ephread/Instructions#187]
**Description:**
`coachMarksController:didHide` reports indexes from `1` not `0` as it correctly should. (`willHide` for instance does report indexes correctly).

**Additional details:**
Regarding the incorrect indexes I have also noticed that when starting flow from `UIViewController:viewWillTransition(to)` (which is triggered when orientation changes) `coachMarkViewsAt` delegate will either report `-1` index (usually when changing from Landscape to Portrait) or double `0` indexes.

Workaround which helped is to run `coachMarksController.start(on: self)` inside `DispatchQueue.main.async`. Even though I did not inspect this bug into the detail I'm pretty sure it should run correctly even without this little "workaround".

**Tested on:**
- 1.2.0

**Comment by ephread** [comment]
Hey @Mattijah , thanks for reporting the issue! It's been known for some time, but I haven't had the chance to fix it yet.

**Comment by RaulOlmedoCheca** [comment]
The Dispatch.async solution provided by @Mattijah also solves another problem that I don't know if its considered a related bug:

The function `coachMarksController::willHide` is executed after `coachMarksController::coachMarkAt`. Is this intentional? If the answer is no, I'll be happy to open a separated issue.
