### ISSUE TITLE
Wrong position coach marks inside a scrollview

### ISSUE THREAD

**Issue by Lailan** [ephread/Instructions#239]
**Describe the bug**

Good afternoon.
I am trying to use the library in my project, but I am facing the following problem:

I have a view that is inside a UIScrollView, when I need to show the coach mark in a place that is not visible, I scroll down the screen but the location of the coach mark is wrong. (See the GIF)

How can I fix this problem?

**Environment:**
 - Device:  iPhone X
 - iOS version: 13
 - Instructions version: master
 - Dependency Manager: CocoaPods

**Example GIF**
![RPReplay_Final1589398754](https://user-images.githubusercontent.com/14180424/81857493-b8d69800-9538-11ea-973b-7312626314d5.gif)

**Comment by ephread** [comment]
Hey there @Lailan, my guess is that the current offset of the scroll view is not taken into account. [The helper making the conversion](https://github.com/ephread/Instructions/blob/master/Sources/Instructions/Helpers/Public/CoachMarkHelper.swift#L138) doesn't work with scroll views, since  —I believe— `UIView.convert` itself ignores the content offset.

The default window and the window used by Instructions share the same coordinates, so you could try to convert the coordinates of your view into its window coordinate system with`UIView.convert` and then manually substract the scrollview offset from its origin.

I should probably add something in the README.

By the way, thanks for taking the time to provide a video, it's really appreciated!

**Comment by Lailan** [comment]
Thanks for the quick response.
Do you have any examples of how I can do this?

**Comment by ephread** [comment]
Maybe something like this, but it's just from the top of my head. I can have a deeper look, but probably not before a few days. I should probably deal with this case in the helper.

```swift
var coachMark = coachMarksController.helper.makeCoachMark(for: pointOfInterest)

let rect = view.window!.convert(viewOfInterest.frame, from: viewOfInterest.superview)
rect = CGRect(x: rect + scrollView.contentOffset.x,
              x: rect + scrollView.contentOffset.y,
              width: rect.width,
              height: rect.height)

coachMark.cutoutPath = UIBezierPath(roundedRect: rect.insetBy(dx: -4, dy: -4),
                                    byRoundingCorners: .allCorners,
                                    cornerRadii: CGSize(width: 4, height: 4))
```

**Comment by Lailan** [comment]
Works!

`let coachMark = coachMarksController.helper.makeCoachMark(for: self.viewAlunos) {
            (frame: CGRect) -> UIBezierPath in
                var rect = self.view.window!.convert(self.viewAlunos.frame, from: self.viewAlunos.superview)
                rect = CGRect(x: rect.origin.x,
                              y: rect.origin.y - bottomOffset.y,
                              width: rect.width,
                              height: rect.height)
                return  UIBezierPath(roundedRect: rect.insetBy(dx: -4, dy: -4),
                                                   byRoundingCorners: .allCorners,
                                                   cornerRadii: CGSize(width: 4, height: 4))
            }`
