### ISSUE TITLE
Scroll view between steps

### ISSUE THREAD

**Issue by negarhaghbin** [ephread/Instructions#264]
## Describe the bug
I'm trying to scroll view between the second and third steps of the walkthrough but no matter where I use `prepareForChange()`  and `restoreAfterChangeDidComplete()` I get `simultaneous access` exception in the second line of `willTransition` function. What am I doing wrong?

## To Reproduce
Use a coachmarkController in a scrollable view and here is how I call the functions:
```swift
func coachMarksController(_ coachMarksController: CoachMarksController, didHide coachMark: CoachMark, at index: Int) {
        if index == 1 {
            coachMarksController.prepareForChange()
            scrollView?.scrollToBottom(animated: true)
            coachMarksController.restoreAfterChangeDidComplete()
        }
    }
```

## Expected behavior
To update coachmark's position and cutout path's position after scrolling is finished.

## Environment
 - Device: iPhone 12 Pro Max
 - iOS version: 15
 - Instructions version: 2.1.0
 - Dependency Manager: CocoaPods

**Comment by ephread** [comment]
Hey @negarhaghbin!

`prepareForChange()` and `restoreAfterChangeDidComplete()` are old and a bit cumbersome, they probably don't play well with Swift 5+ memory safety improvements. I should certainly remove them and improve the documentation. It's recommended that you pause the flow instead, perform the animation, then resume it. The best place to do that is in `willShow` instead of `didHide`.

I don't fully remember what could cause the memory violation, but pausing the flow in `willShow` should not cause any issues.

Based on your code example, bear in mind that if you call `flow.resume()` immediately after `scrollToBottom`, it probably won't work either since it will be executed before the scroll view has had a chance to scroll down (assuming it's animating). `flow.resume()` needs to be called in some sort of completion block.

Here's the basic idea, you can also take a look at `DelegateViewController` in the example directory.

```swift
override func coachMarksController(_ coachMarksController: CoachMarksController,
                                   willShow coachMark: inout CoachMark,
                                   beforeChanging change: ConfigurationChange, at index: Int) {
    if index == 1 && change == .nothing { // The index of the coach mark that needs scrolling.
        coachMarksController.flow.pause()

        // Assuming there's a completion block to `scrollToBottom`.
        scrollView?.scrollToBottom(animated: true) {
            // Once the animation is completed, the coach mark needs to be updated,
            // since its position likely changed.
            coachMarksController.helper.updateCurrentCoachMark(usingView: yourViewOfInterest)
            coachMarksController.flow.resume()
        }
    }
}
```

Sorry about that, the documentation is a bit outdated and somewhat confusing. It needs a fresh coat of paint.

**Comment by negarhaghbin** [comment]
Thanks, @ephread! It's working now. I added the part that was meant for after the scrolling code is completed in `scrollViewDidEndScrollingAnimation` function of `UIScrollViewDelegate`.

```
func scrollViewDidEndScrollingAnimation(_ scrollView: UIScrollView) {
        if coachMarksController.flow.isPaused {
            coachMarksController.helper.updateCurrentCoachMark(usingView: groupOwnerView) { [weak self] frame in
                return self?.getMembersCutoutpath(frame: frame) ?? UIBezierPath(roundedRect: frame, cornerRadius: 0)
            }
            coachMarksController.flow.resume()
        }
    }
```

**Comment by ephread** [comment]
Cheers, that's great to hear!
