### ISSUE TITLE
Adding on TabBarController

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [ephread/Instructions#31]
Hi. how can i add on tabbar controller? thanks you.

**Comment by ephread** [comment]
Hello @AyeChanPyaeSone!

Can you be a little bit more specific? What are your needs? Attaching a `CoachMarkController` to a Container View Controller should normally work in the same way as attaching it to a regular one (even though I haven't tested this behavior).

**Comment by AyeChanPyaeSone** [comment]
I want to show coachmark on tab bar items like this. https://s-media-cache-ak0.pinimg.com/564x/5d/16/da/5d16da83fc7d919e3512f5e59f914bcc.jpg  thanks you so much. Now you are adding the Label and pass that label frame. I cannot pass the parameter as tabbar item coz there is no frame in tab bar item. thanks you.

**Comment by ephread** [comment]
Your issue is a bit similar to the one that arose in a [gitter conversation](https://gitter.im/ephread/Instructions) a couple a months ago.

Indeed, since `UIBarItem` doesn't subclass `UIView` and hold its related view in a private property, you can't easily retrieve the frame. Additionally, I don't believe you can even retrieve a `UIBarItem` from a `UITabBar`. You'll have to work around Apple's private implementation to get the frame and pass it to Instructions.

This [Stack Overflow post](http://stackoverflow.com/questions/6325457/getting-the-frame-of-a-particular-tab-bar-item) (and its related [comment](http://stackoverflow.com/questions/6325457/getting-the-frame-of-a-particular-tab-bar-item#comment27792296_17435146)) may be a starting point.

I won't provide helper for these edge cases, as I don't want to burden the library with code that may (or may not) cause an App Store rejection from Apple.

**Comment by AyeChanPyaeSone** [comment]
Okies. thanks you very much for your help and I do like your library so much. So right now its not possible to add instructions on tab bar. is it?

**Comment by d4kr** [comment]
let view = self.tabBarController?.tabBar.items?[0].valueForKey("view") as? UIView

you get view you need, it works!

**Comment by ephread** [comment]
@AyeChanPyaeSone you can cautiously use it on a `UITabBarController` and definitely use it on one of its child controllers, especially given the solution provided by @d4kr. However, since this solution uses KVO to retrieve a private property, the app _might_ be rejected by Apple.

@d4kr: did you successfully published an app containing this approach?

**Comment by jeeftor** [comment]
I'm looking at the same issue with a tab bar controller

**Comment by d4kr** [comment]
not yet, I used it only for private beta testing. I used the same approach to access to UITabBarItem

let view = self.navigationItem.rightBarButtonItem?.valueForKey("view") as? UIView

I will try with a public very soon...

**Comment by AyeChanPyaeSone** [comment]
@ephread and @d4kr   thanks you so much both of you. :)  let me know if it is okie or not. :+1:

**Comment by d4kr** [comment]
I think is OK, my app was just approved by Apple for public beta.

**Comment by AyeChanPyaeSone** [comment]
thanks you so much!!! @d4kr

**Comment by AyeChanPyaeSone** [comment]
@d4kr you used this code right?? let view = self.tabBarController?.tabBar.items?[0].valueForKey("view") as? UIView

**Comment by sl4m** [comment]
@ephread Have you considered adding a caveat for `UIBarItem`s in the README? I'm looking into this very issue. We may ultimately just not show a coach mark for for a `UIBarItem`. Is this a limitation with the library or in general? Thanks

**Comment by ephread** [comment]
@sl4m totally missed your comment it seems, sorry. The answer you seek is in the [fourth comment of this very thread](https://github.com/ephread/Instructions/issues/31#issuecomment-191788362).

I'm currently considering creating a FAQ, to which the README would be prominently link.
