### ISSUE TITLE
Question regarding the usage of hyphenationFactor

### ISSUE THREAD

**Issue by oferRounds** [ephread/Instructions#49]
Hi!
Two questions please:
1.I'm interested to know what is design reason behind using hyphen word break on `CoachMarkBodyDefaultView`?
2. I see that `hyphenationFactor`'s documentation states that its value should be between 0.0 to 1.0. But I see it is set to 2.0... What is the reason for this?

**Comment by ephread** [comment]
Hello @oferRounds!

1. It's simply because I'm an hyphenation nerd. I believe nothing beats a justified paragraph with good hyphenation, in terms of readability. However, I admit that the hyphenation engine found in TextKit is sometimes lacking.

2. Probably a typo or some experimentation leftovers. This is an oversight. I believe that a value found to be above `1.0` is actually capped to `1.0`.

**Comment by oferRounds** [comment]
Hi @ephread!

Got you - thanks for both replies, and for this really great library!

**Comment by ephread** [comment]
Thanks, you're welcome. ;)
