### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by 99centsappdevelopment** [ephread/Instructions#5]
Are there any plans to release this control for objective-c?

Looks fantastic, by the way!

**Comment by ephread** [comment]
Thanks!

There are plans to support _[mix & match](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)_. :) But I don't know when. It could be implemented in the next week or in the next month. I want to improve the test coverage beforehand!

**Comment by ephread** [comment]
I gave the matter some thoughts and… well, since I use Swift-only features, such as tuples and structures, rewriting the library to use only bridgeable types would not be worth the hassle. However, I (roughly) detailed a possible solution in the [objective-c](/ephread/Instructions/tree/objective-c) branch.

It involves using Swift classes conforming to `CoachMarksControllerDataSource` and `CoachMarksControllerDelegate`, that are themselves bridged to Objective-C. That's how I'm going to use Instructions in my Objective-C projects.

**Comment by ephread** [comment]
I think the question has been answered.

Closing!
