### ISSUE TITLE
Skipping already shown CoachMarks 

### ISSUE THREAD

**Issue by aozbayra** [ephread/Instructions#61]
I wanted to show a coachMark, leave my current controller, come back to it and skip the coachMark that I have already shown to my user. I wanted to make a good use of this delegate function:     
`func coachMarksController(coachMarksController: CoachMarksController, coachMarkWillLoadForIndex index: Int) -> Bool {
        if index <= defaults.integerForKey(GlobalConstants.skipProfileWalkthrough) {
            return false
        }
        return true
}
`
However, it was crashing on this line in your library: 
`self.delegate?.coachMarksController(self, coachMarkWillDisappear: self.currentCoachMark!, forIndex: self.currentIndex - 1)` 
with the following error: 
`fatal error: unexpectedly found nil while unwrapping an Optional value`
It was pretty much trying to wrap self.currentCoachMark that was nil for some reason. 
I fixed it myself on your library and took some notes. Attached you can see the notes I took and the fixes I made on your library:
![note_1](https://cloud.githubusercontent.com/assets/9277891/17370076/aadcf8b2-5968-11e6-9abd-a15a1cf918b0.png)
![note_2](https://cloud.githubusercontent.com/assets/9277891/17370091/b99a7dac-5968-11e6-8347-2c8bf24d463a.png)
![note_3](https://cloud.githubusercontent.com/assets/9277891/17370100/bd81ecc0-5968-11e6-8dab-5a38bea07ac1.png)
Also I am not using your delegate function coachMarkWillDissappear anymore, I do not think that it is working fine, instead I am doing it like this: 
![screen shot 2016-08-02 at 9 22 37 pm](https://cloud.githubusercontent.com/assets/9277891/17370122/db352ad4-5968-11e6-8e72-6e0b223bdb3c.png)

**Comment by ephread** [comment]
Thanks for your clear notes. 🙂

#### First issue
This morning, I fixed the first issue you encountered (c91a37d). My bad, I actually never thought of the case where the first coach mark (at index 0) would be skipped. Instructions was trying to hide the previously displayed coach mark (which was `nil`), and crashed.

Instructions hasn't reached version 1.0.0 yet and I've purposely kept a number of forced unwraps throughout the library, to make issues like these more explicit.

#### Second issue

Cross controller walkthrough is not supported yet. This is, in part, what you are trying to achieve. You need to keep a state in-between controllers, even though you might show coach marks on only one of them. Proper cross controller can be solved in different ways, but I haven't settled on a solution yet. (Non-exhaustive bulk: one `CoachMarksController` per VC, one `CoachMarksController` for everything, library trying to magically handle everything or letting the developer handle its use-case, etc.)

#### Rationale and possible solutions

`reset()` is setting the `currentCoachMark` to `nil`, simply because Instructions does not retain any kind of state between `start()` and `stop()`. `reset()` cleans everything up. This implies that you could theoretically reuse the same `CoachMarksController` to show an entire new set of coach marks, by simply calling `stop()`, swapping the `dataSource` and calling `startOn(_:)` again. I'd very much keep this behavior. `stop()` needs to stop the flow and perform some cleanup.

However, if, some kind of state must be retained, there are two options (your notes were right on track).

1. Let the developer deal with this matter, by providing him with a bugless API 😉. It would take the form of what you're trying to achieve: start from the beginning, but using the delegate to skip some coach marks.

2. Let the library do the heavy lifting; the best solution would probably be to add an optional boolean parameter to `pause()`, which would tell the `CoachMarksController` to detach itself from both the parent view controller and the current window. Then, `resume()` would reattach everything.

I'm still conflicted about the matter. Should it be the responsibility of the developer or should it be the responsibility of the library? I need more time to think this through.

In any case, (c91a37d) should solve your initial problem, by letting you skip the first coach mark.

**Note:** as you found out, `showNext()` can't be used right after `startOn()` without messing things up. It's designed to be called while `CoachMarksController` is waiting for the user to perform an action. Maybe I should make this more explicit in the README.

#### `coachMarkWillDisappear` 

There is indeed an issue on `coachMarkWillDisappear` (it may get wrongly called after size change / rotation), but I am not certain this issue is the one you encountered. Perhaps you were expecting a different behavior? Let me know what was the issue (if unrelated to the above-explained points).

**Comment by aozbayra** [comment]
I agree on your points and what I was expecting on coachMarkWillDisappear was to basically be my helper method where I get to decide whether I should skip the currentCoachMark on the queue or not. That's why I was returning false or true depending on what indexes have been shown to the user. Also I am actually using showNext right after startOn in case I want to skip some of the coachMarks. It is not the preferred way of doing it, I am aware of that however, since coachMarkWillDisappear does not work properly, that's pretty much the only way of doing it. I will keep an eye on your updates and releases and will update my code accordingly. 
Happy to help with your issues, thanks again for the library!
