### ISSUE TITLE
Possible build failure on Carthage due to Unneeded Build Dependency

### ISSUE THREAD

**Issue by toshi0383** [ephread/Instructions#74]
Instruction has swiftlint Run Script Phase inside the xcodeproj.
```
source ~/.profile
if which swiftlint > /dev/null; then
    swiftlint
else
    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```
This potentially causes build error on Carthage.
For example, `~/.profile` is missing in my environment, so Run Script Build Phase failed.

IMO In general, if you are writing a library(not an app), SwiftLint check should be managed outside of xcodeproj.

**Comment by ephread** [comment]
Hey @toshi0383! Thanks a lot for catching this lack of foresight on my part.

The main point of running SwiftLint as a script phase is to get the warning/errors from inside the IDE. The issue here is not the script phase, but rather the fact that it was poorly written (apologies for this, I made wrong assumptions). I'm fairly confident that SwiftLint checks can be managed from inside the `.xcodeproj` without causing build issues.

I will rewrite the script to make it more robust and transparent (i. e. can't make the build fail if `~/.profile` or `swiftlint` aren't found).

**Comment by aloco** [comment]
Hi, I ran into the same issue, I had no `~/.profile`, fixed that by creating an empty `.profile`

**Comment by toshi0383** [comment]
> I will rewrite the script to make it more robust and transparent (i. e. can't make the build fail if ~/.profile or swiftlint aren't found).

No it should be this way. - Don't run swiftlint when building by Carthage.
Because... even the user has SwiftLint installed, how could you tell that SwiftLint future versions won't ever contain a bug ???

I looked over Carthage repo and I didn't know that [they have been injecting env variables into xcodebuild command](https://github.com/Carthage/Carthage/issues/1148).
I will create a PR 👍

**Comment by ephread** [comment]
> No it should be this way. - Don't run swiftlint when building by Carthage.
Because... even the user has SwiftLint installed, how could you tell that SwiftLint future versions won't ever contain a bug ???

We both agree. I certainly failed to express myself properly, as I only meant that the script was not going away and that I would need to rethink the naive version. That included trying to circumvent the use of `swiftlint` while building externally. 😉 

I wasn't aware of `$CARTHAGE`, though.

Thanks a lot for the PR!

**Comment by toshi0383** [comment]
🚀🚢😆
