### ISSUE TITLE
Make CoachMarksController open instead of public

### ISSUE THREAD

**Issue by Damnum** [ephread/Instructions#77]
With Swift 3, the `CoachMarksController` and its `public` methods cannot be inherited. This is important in order to create fakes/mocks to test dependent classes. (all my tests are broken now)

Would be great to change the class and its `public` methods to `open`.

**Comment by ephread** [comment]
Using `public` rather than `open` was a conscious decision, to keep things tidy, but maybe it was a wrong one. I don't really see any argument against making these methods `open`, so if you really need it, we can make it happen.

That said, I think you should try to avoid mocking a type you don't fully own in your codebase.

Can you make a PR with the changes?

**Comment by Damnum** [comment]
@ephread interesting point. The alternative would be to write a wrapper around the class and fake that in turn. 

But especially with the controller I could also see use cases to extend it in order to add functionality. The UIKit View Controllers are also `open` rather than `public`.

I'll make the PR.

**Comment by Damnum** [comment]
Never mind, I just realized that the methods in question are inside an extension, and those can't be overridden anyway.

I ended up writing a wrapper around the class. Thanks for your swift response though!
