### ISSUE TITLE
Customizing view cutout

### ISSUE THREAD

**Issue by LeonardBonfils** [ephread/Instructions#8]
Hey,

Thanks a lot for this library. I was wondering if you could tell me how to customize the cutout path. Here's a screenshot of what I'm getting.

http://imgur.com/q26iERN

I would really like to "cut" the three edges that are visible in my cutout. On the bottom and on the right side of my visible view, I have black bars. And at the top, I have a yellow bar. I've also got a small yellow portion at the bottom-right portion of the visible view. I would like to customize the visible view cutout so that all I see is the center yellow part. I just need to cut the little bits that are on the sides, to make it look cleaner, and uni-coloured. How can I do that ?

Merci beaucoup de nous fournir cette ressource géniale. Cela me fait économiser énormément de temps pour mon premier project sérieux avec Swift et iOS.

Merci,
Un concitoyen originaire du 92 :)

**Comment by ephread** [comment]
Je t'en prie !

If I understand your question correctly, you only need to provide a block returning the appropriate `UIBezierPath` to `coachMarkForView(_:UIView)` (as stated [here](https://github.com/ephread/Instructions#providing-a-custom-cutout-path)).

If you want the cutout path to equal the frame of the given view, you can use the following code:

```swift
var coachMark = coachMarksController.coachMarkForView(customView) {
(frame: CGRect) -> UIBezierPath in
    return UIBezierPath(rect: frame)
}
```

On a side note, since you're using the blurring overlay, please know that I plan to improve its look. Rather than using a cutout path, you'll be able to tell Instructions to rasterise the view and display the rasterised copy above the overlay. It'll look much better for text and complex icons.

In the future, if you need more help, please ask your question on Stack Overflow with the `instructions-swift` tag or on the [gitter chat](https://gitter.im/ephread/Instructions). Stack Overflow is preferable, because it allows everyone else with the same question to find the answer. :)

Let's keep the GitHub issues solely for bug reports and feature requests! I know, I know, I forgot to clarify that in the README, my bad… I will add a “Asking Questions” section when I'll get the chance.

**Comment by LeonardBonfils** [comment]
This really does not seem to be working. (the UIBezierPath function). It is selecting the right view (my button subview...) but it's just not applying the right frame "selection". Even if I use CGRectInset with delta values of like -4000, it doesn't move at all. What could be wrong ?

Here is my code

            var coachMark = coachMarksController.coachMarkForView(self.view.viewWithTag(1)) {
            (frame: CGRect) -> UIBezierPath in
            return UIBezierPath(rect: frame)
        }

The view I am selecting with the tag is simply the button, which is a subview of my "view" item.

**Comment by ephread** [comment]
Tricky, tricky. The `cutoutPath` may somehow be overriden. It might be a bug in the library, but I've checked again and all the examples work properly.

- You're not doing anything fancy, are you (such as calling `updateCoachMark`)?
- Which version of Instructions do you use?
- Can you confirm that, if you download the [project](https://github.com/ephread/Instructions/releases/tag/0.3.0), and tweak the examples, they show the expected behaviour? (You can, for instance, edit the datasource methods in `DefaultViewController.swift`.)

**Comment by ephread** [comment]
@LeonardBonfils any update on your issue? Did you solved it on your own?

**Comment by LeonardBonfils** [comment]
Unfortunately, I was not able to get it to work. I just accepted the fact that it doesn't cut out the view properly. Maybe I'll give it another shot later, before releasing my update.

On Nov 10, 2015, at 04:43, Fr?d?ric Maquin <notifications@github.com<mailto:notifications@github.com>> wrote:


@LeonardBonfils<https://github.com/LeonardBonfils> any update on your issue? Did you solved it on your own?

-

**Comment by ephread** [comment]
It should work. There might be a bug in the library, which I would gladly fix, if you could provide me with more information. :) I'll close the issue for the time being, feel free to re-open it later!
