### ISSUE TITLE
blurEffectStyle not working on iOS 10

### ISSUE THREAD

**Issue by techseeko** [ephread/Instructions#80]
It's a problem out there, for iOS 10, UIVisualEffectView does not blur when using UIBlurEffect in some cases. If anything is added to the UIVisualEffectView directly it might break the functionality, it should always be added to the UIVisualEffectView.contentView.

Also the presentationStyle should not be CrossDissolve this kind of view should be animated via UIView animation while setting the effect.

Can you please fix? If there's a workaround or anything that might help in this.

PS: Once we set the blurEffectStyle to .Dark all the views behind will show normally without blur effect, the background gets a bit darker, but it's not the intended behaviour since we can still read the text behind clearly and it affects all coach mark texts.

**Comment by ephread** [comment]
Thanks for reporting the issue @techseeko. The `UIVisualEffectView` support indeed remains a bit sketchy due to a lack of time on my end.

> If anything is added to the UIVisualEffectView directly it might break the functionality, it should always be added to the UIVisualEffectView.contentView.

Nothing is added to the `UIVisualEffectView`, the layer is manipulated and a mask is created. This is certainly what's causing the issue. I discovered few weeks ago that Apple now recommends to use the `maskView` property to create masks but I haven't had the time to look into it. This [thread](https://forums.developer.apple.com/thread/50854) is especially interesting if you wish to fix the issue yourself (also take a look at [OverlayView](https://github.com/ephread/Instructions/blob/master/Sources/Views/OverlayView.swift) and [OverlayViewLayerManager](https://github.com/ephread/Instructions/blob/master/Sources/Managers/OverlayViewLayerManager.swift)).

> Also the presentationStyle should not be CrossDissolve this kind of view should be animated via UIView animation while setting the effect.

Due to limitations encountered at the time of iOS 8, the coach marks are not _presented_. Rather, everything is attached to the window. I've never been totally okay with this approach and I hope that, when dropping iOS 8, I'll be able to use window levels and presented view controllers mechanics.

**Comment by Anders123fr** [comment]
Does anyone have a fix for this ?

**Comment by ephread** [comment]
@Anders123fr: I'm currently working on it. It requires some non trivial changes to the library, since the `mask` property on `UIView` is not animatable.

**Comment by Anders123fr** [comment]
Yeah I can imagine, but sounds great that you are working on it :)

**Comment by mureatencio** [comment]
Any fix for this behavior?

**Comment by ephread** [comment]
Should now be fixed in `master`, a release will come tomorrow. It's not perfect (could use further optimization), but it works.
