### ISSUE TITLE
Crashing When in Landscape Mode at Startup

### ISSUE THREAD

**Issue by rimckenn** [ephread/Instructions#91]
Instructions framework is crashing when force unwrapping an optional when starting it up in landscape orientation:

https://github.com/ephread/Instructions/blob/master/Sources/Managers/FlowManager.swift#L249

I fixed it locally by testing the optional first, but not sure if this is the preferred solution:

```
if let coachMark = currentCoachMark {
    coachMarksViewController.hide(coachMark: coachMark, animated: false)
}
```

Thanks.

**Comment by rimckenn** [comment]
The checking of the optional alone prevents a crash, but the views get messed up. It seems that viewWillTransition gets unexpectedly called at startup which is causing issues. I additionally added the following check to 

https://github.com/ephread/Instructions/blob/master/Sources/Controllers/CoachMarksViewController.swift#L216

`if currentCoachMarkView == nil {
    return
}`

This seems to resolve the issue, but probably best if somebody who knows the code could check if this seems ok.

**Comment by ephread** [comment]
Thanks for reporting the issue @rimckenn!

Indeed, the force unwrapping is there to make an unrecoverable state explicit (Instructions still hasn't reached 1.0.0), as `currentCoachMarkView` should not be nil at this point. It forces us to look for the underlying issue, rather than optionally unwrapping the value.

Your fix seems entirely rational to me, can you make a PR out of it (and credit yourself in AUTHORS and in the file header)?

**Comment by rimckenn** [comment]
Sure, I just created one there. Thanks!

**Comment by ephread** [comment]
Closing, PR #93 fixes the issue.
