### ISSUE TITLE
Is it possible to use this library in Objective-C project with Xcode 8?

### ISSUE THREAD

**Issue by LiborZ** [ephread/Instructions#95]
I have Objective-C project that until now was using only Objective-C. I like this library and I would like to use it in my project. I am using CocoaPods for external frameworks. I want to first test import this library with new project. So I created new project ObjectiveCTestProject and set podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjectiveCTestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods
 for ObjectiveCTestProject
  
  pod 'Instructions', :git => 'https://github.com/ephread/Instructions', :branch => 'swift3'
end
```

I get dialog with converting to Swift 3 which is weird but I click at Convert and project builds fine. But when I try use classes from Instructions I get error that class could not be found.

I tried to import Instructions to Objective-C file:
`#import <Instructions/Instructions-Swift.h>`
or
`#import "ObjectiveCTestProject-Swift.h"`
or
`@import Instructions;`
but nothing works. I tried even other branches ("objective-c" - but it has old swift files for Xcode 8). Can you help me? Thanks

**Comment by ephread** [comment]
Hey @LiborZ, I've updated the `objective-c` branch for Xcode 8 / Swift 3. Can you try to run the test project and report back? Thanks! ;)

By the way, you should use the `master` branch, `swift3` is outdated and will be removed in the future.

The second import (`#import "ObjectiveCTestProject-Swift.h"`) is, if I recall correctly, the right one. That's a tricky subject. Everything is working fine with the test project (using Frameworks), but some people had troubles using Instructions with Objective-C in the past.

Perhaps you should check the build settings, under **Swift Compiler – General** and make sure the generated header matches your import statement.

![screen shot 2017-01-31 at 17 33 26](https://cloud.githubusercontent.com/assets/722366/22474362/df1d569c-e7db-11e6-9cb8-e5cc1b0c382e.png)

CocoaPods may also be the culprit here (although unlikely), as I never really tested the combination of CocoaPods, Instructions and Objective-C code.

**Comment by LiborZ** [comment]
Thanks for your response and for your update. I tried it with my test project and I looked at your Objective-C example and I get it working. I used same aproach as you with InstructionsManager. If I get it right I can't use your classes "direct" in my Objective-C files because they are not mark with @objc so I must for each controller create InstructionsManager and then this manager use in my classes, am I right? So this way it would works for master branch too right? So what's difference between master and objective-c branch? I like swift but I have bad experience with build time in swift projects so I want to make minimum swift files in my project for now (or hope these managers classes won't do much difference).

**Comment by ephread** [comment]
Yes, you can't use Instructions directly within Objective-C, since it exposes unbridgeable swift types (namely structs and tuples) through the public API. You can't mark a `struct` with `@objc`, for instance. You'll need a bit a swift glue, as shown in the `objective-c` branch, to make everything work.

The `objective-c` branch only demonstrates a way to use Instructions with Objective-C, it doesn't provide anything different from `master`. It may eventually be merged back. You should indeed use the `master` branch in your Podfile.

I'm fairly confident that a couple of Swift files in your project won't significantly adverse the compile time. ;) You could also import Instructions as a Framework (manually or through Carthage), which would prevent it from being recompiled too often (depending on Xcode's mood).

**Comment by LiborZ** [comment]
Thanks for all informations and help.
